### ISSUE TITLE
python setup.py build_grpc is not executing anything

### ISSUE THREAD

**Issue by vishaldhanani** [CZ-NIC/setuptools-grpc#3]
Hello,

I have cloned this repo and running locally to compile protobuf file into python but I'm getting the below error.  Can you please share proper documentation in more detail? 
<img width="395" alt="image" src="https://user-images.githubusercontent.com/29518449/209008998-faf9a767-2019-4cd4-b1cd-1740e5b4c5eb.png">

Thank you,
Vishal

**Comment by stinovlas** [comment]
It seems that you didn't install `setuptools-grpc` to the environment from which you try to call `setup.py build_grpc`. Command will be available when you install the `setuptools-grpc` package via `pip`.

Please not that this package is primarily focused to provide automatic build of grpc modules during packaging (and it requires configuration as described in README). If you just want to compile gprc module once, you may use `grpc_tools.protoc` directly (try `python -m grpc_tools.protoc --help`).

**Comment by stinovlas** [comment]
Since there hasn't been any activity for a while, I'm closing this. If you encounter any more problems, feel free to open a new issue.
