### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by Utosz** [CZ-NIC/setuptools-grpc#8]
Hi, 
i have question/problem.
Im trying to use setuptools-grpc for bit denser proto files/folders structure.

My grpc structure looks like that and it is in root of project's directory
![image](https://github.com/CZ-NIC/setuptools-grpc/assets/44579582/fc19512e-5dd6-45f7-8ead-58e5c97330f8)
so i have .proto files for different services and its messages in specific directories.

My setup.cfg looks like that:
![image](https://github.com/CZ-NIC/setuptools-grpc/assets/44579582/d8f1749b-32a7-4551-8bc9-47f2952cee45)
and when im using a tool for this config it is failing.

I debug a code and i found that `filename` created from `glob` are scalped from first character, so im getting list of files like that:
![image](https://github.com/CZ-NIC/setuptools-grpc/assets/44579582/45f774db-8b84-4daf-8be0-498270defac7)

this prints are from `finalize_options()`:
![image](https://github.com/CZ-NIC/setuptools-grpc/assets/44579582/d26f27c7-5536-4417-b0da-e64322bc6bb0)

The question is:
why do we have this +1 in index for filename? 
If i remove it, it works correctly and proper package is built. Should setup.cfg be set differently for my  or its a bug?

**Comment by stinovlas** [comment]
> The question is: why do we have this +1 in index for filename? If i remove it, it works correctly and proper package is built. Should setup.cfg be set differently for my or its a bug?

Hi! Thanks for raising the issue. I believe that the `+1` is there to include trailing slash. Try setting `grpc_path = ./grpc` (without trailing slash). Does that fix your problem?

It's not a very elegant solution indeed. I'll try to devise something more elegant (stripping the `proto_path` prefix), but in the meantime setting `grpc_path` without trailing slash should be a viable workaround.

**Comment by Utosz** [comment]
Thanks, it works!
